services:
  macos:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_LOCK_PASSWORD: ${NEXT_PUBLIC_LOCK_PASSWORD}
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./ctrf:/app/ctrf
    restart: unless-stopped