name: E2E Playwright

on:
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build app image
        run: docker build -t macos-web-desktop .

      - name: Run app
        run: docker run -d -p 3000:3000 macos-web-desktop

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        env:
          PLAYWRIGHT_BASE_URL: http://localhost:3000
        run: yarn test-line
