name: E2E Playwright

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Create missing .env files
        run: |
          cp .env.dist .env
          echo "NEXT_PUBLIC_LOCK_PASSWORD=aurora" >> .env
          echo "PLAYWRIGHT_BASE_URL=http://localhost:8000" >> .env

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare Yarn (lock version)
        run: corepack prepare yarn@4.11.0 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Start app (prod container)
        run: make prod

      - name: Wait for app
        run: |
          echo "Waiting for http://localhost:8000 ..."
          until curl -s http://localhost:8000 > /dev/null; do
            sleep 2
          done

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: make test

      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: 'ctrf/ctrf-report.json'
          summary-delta-report: true
          insights-report: true
          flaky-rate-report: true
          fail-rate-report: true
          slowest-report: true
          upload-artifact: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()

      - name: Upload Playwright screenshots & traces
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: playwright-artifacts
          path: |
            test-results/**

      - name: Stop containers
        if: always()
        run: make prod-stop
